root = "."
tmp_dir = "/tmp"

[build]
  bin = "./tmp/main"
  cmd = "templ generate && go build -o ./tmp/main ."
  exclude_dir = ["assets", "tmp", "vendor"]
  exclude_regex = [".*_templ.go"]
  include_ext = ["go", "tpl", "tmpl", "templ", "html"]
  log = "build-errors.log"
  stop_on_error = true

[color]
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = true

[misc]
  clean_on_exit = true
